i18n.RegisterPhrases("en", {
    gbSystemName = "Glorified Banking",
    gbLoading = "LOADING",
    gbEnterCard = "ENTER YOUR CARD",
    gbToContinue = "TO CONTINUE",
    gbAtmDisabled = "THIS ATM HAS BEEN TEMPORAIRILY DISABLED\nSORRY FOR ANY INCONVENIENCE",
    gbBackShortly = "OUR SYSTEMS WILL BE BACK ONLINE SHORTLY",
    gbWelcomeBack = "WELCOME BACK, %s!",
    gbMenuWithdraw = "WITHDRAW",
    gbMenuDeposit = "DEPOSIT",
    gbMenuTransfer = "TRANSFER",
    gbMenuTransactions = "TRANSACTIONS",
    gbMenuSettings = "SETTINGS",

    gbDarkTheme = "Dark",
    gbWithdraw = "Withdraw",
    gbDeposit = "Deposit",
    gbTransfer = "Transfer",
    gbActions = "ACTIONS",
    gbInterestReceived = "You received %s in interest.",
    gbSalaryToBank = "Your salary of %s was transferred to your bank.",
    gbDropMoneyOnDeath = "You paid %s in hospital bills.",
    gbCashWithdrawn = "You withdrew %s.",
    gbCashDeposited = "You deposited %s.",
    gbCashTransferred = "You transferred %s to %s."
})
